### ISSUE TITLE
Update mime version to avoid fs.readFileSync is not a function error

### ISSUE THREAD

**Issue by aarohmankad** [jergason/intimidate#14]
As of now, `mime@~1.2.9` has a couple of calls to `mime#load()`, which uses the `fs` module.

However, when using `intimidate` in a client-side application, such as a react application, the `fs` module is not globally available. The calls to `mime#load()` then return an error that does not allow use of the `intimidate` module in a client application.

This can be fixed by allowing an update of the `mime` module dependency to the latest version: `mime@^1.2.9`. (Ideally `mime@^1.3.6`)

**Comment by jergason** [comment]
Thanks for your pull request!
